name: Build
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_PRIVATE_KEY }}
        run: |
          mkdir -p ~\.ssh
          echo "$env:SSH_PRIVATE_KEY" > ~\.ssh\production_key
          icacls ~\.ssh\production_key /inheritance:r /grant:r "$env:USERNAME:(R)"
          ssh-keyscan github.com >> ~\.ssh\known_hosts
        shell: powershell

      - name: Install pyInstaller
        run: pip install pyinstaller

      - name: Build the app
        run: pyinstaller --onefile src/main.py

      - name: Publish the app
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Publier le binaire généré par PyInstaller"
          git push origin HEAD:${{ github.ref_name }}