name: Build
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install pyInstaller
        run: pip install pyinstaller

      - name: Build the app
        run: pyinstaller --onefile src/main.py

      - name: Publish the app
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Publier le binaire généré par PyInstaller"
          git push origin HEAD:${{ github.ref_name }}